##
# General
##
name: Minimal-Block
description: "Minimalistic, friendly, responsive."
baseurl:
url: "http://beeryardtech.github.io"

markdown: kramdown
highlighter: rouge

paginate: 5
permalink: /:title

##
# Social share and comments.
##
disqus-id: beeryardtech
twitter: beeryardtech
github: beeryardtech
google: +beeryardtech

# RSS feed
rss-feed-limit: 10
rss-show-full: "no"
