##
# General
##
name: Beeryard Technology
description: "Simple Solutions for Complex Problems."
baseurl:
url: "http://beeryardtech.github.io"

markdown: kramdown
highlighter: rouge

paginate: 10
permalink: /:title

##
# Social share and comments.
##
#disqus-id: beeryardtech
twitter: beeryardtech
github: beeryardtech
google: +beeryardtech

# RSS feed
rss-feed-limit: 10
rss-show-full: "no"

##
# Dependencies
##
gems: [ "jekyll-paginate" ]
